trigger: none

variables:
  PROJECT: 'LabTeste'
  ENVIRONMENT: 'Prod'
  BUILD_ID: 'latest'
  ENVIRONMENT_PARAM: 'prod'

stages:
  - stage: AutoPack
    displayName: AutoPack
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-22.04'
        steps:
          - checkout: self

          - bash: |
              curl -fsS https://tools.veracode.com/veracode-cli/install | sh
              ./veracode package --source . --output artifacts/$(BUILD_ID) --trust

              # Extrai todos os zips encontrados recursivamente
              find artifacts/$(BUILD_ID) -type f -name "*.zip" | while read filename; do
                unzip -o -d "$(dirname "$filename")" "$filename"
              done

              # Remove todos os zips encontrados recursivamente
              find artifacts/$(BUILD_ID) -type f -name "*.zip" -delete

              # Gera o analysisPack.zip com todo o conteúdo do output
              cd artifacts/$(BUILD_ID)
              zip -r analysisPack.zip .
              cd -
            displayName: Instalar CLI e Autopack Veracode

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'artifacts/$(BUILD_ID)'
              ArtifactName: 'analysisPack'
              publishLocation: 'Container'

  - stage: SCA
    displayName: Veracode SCA
    jobs:
      - job: SCA
        pool:
          vmImage: 'ubuntu-22.04'
        steps:
          - checkout: self
          - bash: curl -sSL https://download.sourceclear.com/ci.sh | bash -s -- scan --update-advisor --allow-dirty
            env:
              SRCCLR_API_TOKEN: $(SCA)

  - stage: Scan
    displayName: Veracode Scan
    dependsOn: AutoPack
    jobs:
      - job: Scan
        pool:
          vmImage: 'ubuntu-22.04'
        steps:
          - download: current
            artifact: analysisPack

          - bash: |
              if [ -f "analysisPack.zip" ]; then
                echo "##vso[task.setvariable variable=artifact_file]analysisPack.zip"
              else
                echo "Erro: analysisPack.zip não encontrado"
                exit 1
              fi
            displayName: Detectar Arquivo

          - bash: veracode-pipeline-scan -vid $(APIID_VERACODE) -vkey $(APIKEY_VERACODE) -file $(artifact_file) -fail_build true
            displayName: Executar Veracode Pipeline Scan

  - stage: SAST
    displayName: Veracode SAST
    dependsOn: AutoPack
    jobs:
      - job: SAST
        pool:
          vmImage: 'ubuntu-22.04'
        steps:
          - download: current
            artifact: analysisPack

          - bash: curl -O -L https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/24.7.14.0/vosp-api-wrappers-java-24.7.14.0.jar
            displayName: Baixar Wrapper

          - bash: |
              declare -A PROJECT_MAP=( ["nomeprojeto1"]="novonomeprojeto" ["nomeprojeto02"]="novonomeprojeto02" )
              FINAL_PROJ=${PROJECT_MAP[$PROJ]:-$PROJ}
              echo "##vso[task.setvariable variable=PROJECT_SUB]$FINAL_PROJ"
            displayName: Substituir Nome do Projeto

          - bash: |
              ARTIFACT="analysisPack.zip"
              if [ ! -f "$ARTIFACT" ]; then
                echo "Erro: analysisPack.zip não encontrado"
                exit 1
              fi
              if [ "$(ENVIRONMENT_PARAM)" == "prod" ]; then
                java -jar vosp-api-wrappers-java-24.7.14.0.jar \
                  -vid $(APIID_VERACODE) -vkey $(APIKEY_VERACODE) \
                  -action uploadandscan \
                  -appname "$(PROJECT_SUB)" \
                  -version "$(BUILD_ID)" \
                  -filepath "$ARTIFACT" \
                  -createprofile true \
                  -deleteincompletescan 2 \
                  -createsandbox false
              else
                java -jar vosp-api-wrappers-java-24.7.14.0.jar \
                  -vid $(APIID_VERACODE) -vkey $(APIKEY_VERACODE) \
                  -action uploadandscan \
                  -appname "$(PROJECT_SUB)" \
                  -version "$(BUILD_ID)" \
                  -filepath "$ARTIFACT" \
                  -createprofile true \
                  -deleteincompletescan 2 \
                  -createsandbox true \
                  -sandboxname "$(ENVIRONMENT_PARAM)"
            displayName: Executar Veracode SAST
