trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    # Criar diretório de trabalho
    mkdir -p $(Pipeline.Workspace)/dsmcli
    cd $(Pipeline.Workspace)/dsmcli
    
    # Clonar o repositório
    git clone https://github.com/senhasegura/dsmcli.git .
    
    # Criar arquivo de configuração
    cat > .config.yml << EOF
    auth:
      url: $(DSM_URL)
      client-id: $(DSM_CLIENT_ID)
      client-secret: $(DSM_CLIENT_SECRET)
    EOF
    
    # Executar o DSM CLI
    ./dsm runb \
      --app-name $(APPLICATION) \
      --system $(SYSTEM) \
      --environment $(ENVIRONMENT) \
      --config .config.yml \
      --tool azure-devops -v
  displayName: 'DSM CLI Running Belt execution'
  env:
    APPLICATION: $(APPLICATION)
    SYSTEM: $(SYSTEM)
    ENVIRONMENT: $(ENVIRONMENT)
    DSM_URL: $(DSM_URL)
    DSM_CLIENT_ID: $(DSM_CLIENT_ID)
    DSM_CLIENT_SECRET: $(DSM_CLIENT_SECRET)